# This file contains information about the device associated with this repo
# This is a .properties file, but is also interpreted as a Makefile,
# so keep the syntax simple: NAME=VALUE
DEV_MFR=GizmoTek
DEV_NAME=Gizmo
DEV_PN=1234
DEV_VER=1
DEV_TAG=GizmoTek_Gizmo_1234_v1
